import React from 'react';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

const font = Jost({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
